//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerApp.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born in Rum near Innsbruck.
        /// </summary>
        public static string _1986Body {
            get {
                return ResourceManager.GetString("1986Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth.
        /// </summary>
        public static string _1986Title {
            get {
                return ResourceManager.GetString("1986Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of my school career.
        /// </summary>
        public static string _1993Body {
            get {
                return ResourceManager.GetString("1993Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary school.
        /// </summary>
        public static string _1993Title {
            get {
                return ResourceManager.GetString("1993Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the 3rd class here i knew, i want to start my work career with computers as soon as possible..
        /// </summary>
        public static string _1997Body {
            get {
                return ResourceManager.GetString("1997Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary school.
        /// </summary>
        public static string _1997Title {
            get {
                return ResourceManager.GetString("1997Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s why i visited all computer relevant classes here..
        /// </summary>
        public static string _2001Body {
            get {
                return ResourceManager.GetString("2001Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polytechnic course.
        /// </summary>
        public static string _2001Title {
            get {
                return ResourceManager.GetString("2001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted and supported from AMS i still visited this course.&lt;br /&gt;I used the internship-weeks to prove companies how i work..
        /// </summary>
        public static string _200208Body {
            get {
                return ResourceManager.GetString("200208Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career orientation course.
        /// </summary>
        public static string _200208Title {
            get {
                return ResourceManager.GetString("200208Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KTW offered a course for future computer technicians..
        /// </summary>
        public static string _200209Body {
            get {
                return ResourceManager.GetString("200209Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT course.
        /// </summary>
        public static string _200209Title {
            get {
                return ResourceManager.GetString("200209Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to the intership-weeks i found a position for an apprenticeship at MED-EL..
        /// </summary>
        public static string _200212Body {
            get {
                return ResourceManager.GetString("200212Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprenticeship.
        /// </summary>
        public static string _200212Title {
            get {
                return ResourceManager.GetString("200212Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile independency, thanks to successful driving license exam (L17).
        /// </summary>
        public static string _2004Body {
            get {
                return ResourceManager.GetString("2004Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license.
        /// </summary>
        public static string _2004Title {
            get {
                return ResourceManager.GetString("2004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 months military service at Lienz&lt;br /&gt;After the base training i joined the guard squad till the end.&lt;br /&gt;Where i succesfully finished the guard commander training..
        /// </summary>
        public static string _2006Body {
            get {
                return ResourceManager.GetString("2006Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military service.
        /// </summary>
        public static string _2006Title {
            get {
                return ResourceManager.GetString("2006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the military service and a one week vacation, i re-joined MED-EL as an IT-Helpdesk employee..
        /// </summary>
        public static string _2007Body {
            get {
                return ResourceManager.GetString("2007Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-Helpdesk.
        /// </summary>
        public static string _2007Title {
            get {
                return ResourceManager.GetString("2007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even more mobile independency with the motorcycle license added to the driving license..
        /// </summary>
        public static string _2010Body {
            get {
                return ResourceManager.GetString("2010Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle driving license.
        /// </summary>
        public static string _2010Title {
            get {
                return ResourceManager.GetString("2010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 15 years experience within the Helpdesk and some more special topics (Sharepoint, Linux, Exchange, ...) i got promoted to the System Administration..
        /// </summary>
        public static string _201703Body {
            get {
                return ResourceManager.GetString("201703Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administration.
        /// </summary>
        public static string _201703Title {
            get {
                return ResourceManager.GetString("201703Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After some organizational changes within the department, i moved to Business Applications together with the Sharepoint topic.
        /// </summary>
        public static string _201710Body {
            get {
                return ResourceManager.GetString("201710Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Applications.
        /// </summary>
        public static string _201710Title {
            get {
                return ResourceManager.GetString("201710Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again organizational changes and time to move. Now i switched to the Digital Development department.&lt;br /&gt; Here i had the first contact with SCRUM, CRM, Power Platform and coding..
        /// </summary>
        public static string _201712Body {
            get {
                return ResourceManager.GetString("201712Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Development.
        /// </summary>
        public static string _201712Title {
            get {
                return ResourceManager.GetString("201712Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right before the Corona Pandamic hit us that hard, i was lucky and got my first dog.&lt;br /&gt;More on the Dog site..
        /// </summary>
        public static string _2020Body {
            get {
                return ResourceManager.GetString("2020Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First dog.
        /// </summary>
        public static string _2020Title {
            get {
                return ResourceManager.GetString("2020Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department change again. Back to the IT with again new challenges and responsibilities.&lt;br /&gt;As Cloud System Administrator again new topics (besides Sharepoint).&lt;br /&gt;&lt;ul&gt;&lt;li&gt;Azure&lt;/li&gt;&lt;li&gt;Box&lt;/li&gt;&lt;li&gt;Power Platform&lt;/li&gt;&lt;li&gt;AWS&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string _202104Body {
            get {
                return ResourceManager.GetString("202104Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administration.
        /// </summary>
        public static string _202104Title {
            get {
                return ResourceManager.GetString("202104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the Software Developer with C# course at the WIFI Innsbruck.&lt;br /&gt;After 3 years without developing, i start through again.&lt;br /&gt;Thanks to this course i was motivated to create a new Website for me..
        /// </summary>
        public static string _202110Body {
            get {
                return ResourceManager.GetString("202110Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Software Developer.
        /// </summary>
        public static string _202110Title {
            get {
                return ResourceManager.GetString("202110Title", resourceCulture);
            }
        }
    }
}
