//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerApp.Resources.Coding", typeof(Coding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                            &lt;li&gt;- Basics&lt;/li&gt;
        ///                            &lt;li&gt;- Entity Framework&lt;/li&gt;
        ///                            &lt;li&gt;- Xamarin&lt;/li&gt;
        ///                            &lt;li&gt;- Blazor/Razor&lt;/li&gt;
        ///                            &lt;li&gt;- WebAPI&lt;/li&gt;
        ///                        &lt;/ul&gt;.
        /// </summary>
        public static string S1C1Body {
            get {
                return ResourceManager.GetString("S1C1Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# / ASP.NET.
        /// </summary>
        public static string S1C1Title {
            get {
                return ResourceManager.GetString("S1C1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote a bunch of complex scripts, to make our lifes easier. Mainly for our Active Directory and our Exchange System. But also a few SharePoint Scripts..
        /// </summary>
        public static string S1C2Body {
            get {
                return ResourceManager.GetString("S1C2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell.
        /// </summary>
        public static string S1C2Title {
            get {
                return ResourceManager.GetString("S1C2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since Sharepoint 2007 I&apos;m the main responsable person for our SharePoint Infrastructure. Migrated our Sharepoint content from 2007 to 2010, then to 2016 and now towards Sharepoint Online..
        /// </summary>
        public static string S1C3Body {
            get {
                return ResourceManager.GetString("S1C3Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint.
        /// </summary>
        public static string S1C3Title {
            get {
                return ResourceManager.GetString("S1C3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With CRM and my C# course i got the basic skills and knowledge about SQL. With more private C# projects these skills will be refined..
        /// </summary>
        public static string S1C4Body {
            get {
                return ResourceManager.GetString("S1C4Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string S1C4Title {
            get {
                return ResourceManager.GetString("S1C4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly used git for my &lt;a href=&quot;https://github.com/rerlache&quot; target=&quot;_blank&quot;&gt;personal Projects&lt;/a&gt; and with the Developer Course. Until now, not so much with a team and branches..
        /// </summary>
        public static string S1C5Body {
            get {
                return ResourceManager.GetString("S1C5Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git and Github.
        /// </summary>
        public static string S1C5Title {
            get {
                return ResourceManager.GetString("S1C5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started working with SCRUM with my Departmentchange. I really enjoy working with this framework, as you (personally) and the team get more productive from Sprint to Sprint..
        /// </summary>
        public static string S1C6Body {
            get {
                return ResourceManager.GetString("S1C6Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRUM.
        /// </summary>
        public static string S1C6Title {
            get {
                return ResourceManager.GetString("S1C6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probably a bit rusty on that part, as i don&apos;t need that too much..
        /// </summary>
        public static string S1C7Body {
            get {
                return ResourceManager.GetString("S1C7Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML and CSS.
        /// </summary>
        public static string S1C7Title {
            get {
                return ResourceManager.GetString("S1C7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly worked with Windows OS. Started with Windows 95. Skipped Vista and Windows 8..
        /// </summary>
        public static string S2C1Body {
            get {
                return ResourceManager.GetString("S2C1Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly worked on our local Trac/SVN Server (Apache + SVN plugins). Semi-Automated some work there with scripts..
        /// </summary>
        public static string S2C2Body {
            get {
                return ResourceManager.GetString("S2C2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                            &lt;li&gt;- 2007&lt;/li&gt;
        ///                            &lt;li&gt;- 2010&lt;/li&gt;
        ///                            &lt;li&gt;- 2016&lt;/li&gt;
        ///                            &lt;li&gt;- Online&lt;/li&gt;
        ///                        &lt;/ul&gt;.
        /// </summary>
        public static string S2C3Body {
            get {
                return ResourceManager.GetString("S2C3Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked on the WebGUI as well as with Powershell with Exchange Onprem and Online. Created a bunch of Powershell scripts to make my life easier..
        /// </summary>
        public static string S2C4Body {
            get {
                return ResourceManager.GetString("S2C4Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked on the GUI as well as with Powershell on our local Active Directory. Created a bunch of Powershell scripts to make my life easier..
        /// </summary>
        public static string S2C5Body {
            get {
                return ResourceManager.GetString("S2C5Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used the PowerPlatform for a few Projects to make processes better, more modern and more automated. Mainly used PowerApps and Automate in combination with SharePoint and Dataverse..
        /// </summary>
        public static string S2C6Body {
            get {
                return ResourceManager.GetString("S2C6Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did mainly Support tasks for our CRM System, but also some Processes, Form and Backend changes..
        /// </summary>
        public static string S2C7Body {
            get {
                return ResourceManager.GetString("S2C7Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As work moves more and more towards the cloud, the need of Azure know-how is mandatory. So my Azure knowledge is growing day by day..
        /// </summary>
        public static string S2C8Body {
            get {
                return ResourceManager.GetString("S2C8Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational and Usage. As i&apos;m responsable for our organization projects, i know the operational part and as we work with SCRUM i also know a bit of the Usage part..
        /// </summary>
        public static string S2C9Body {
            get {
                return ResourceManager.GetString("S2C9Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks, Technologies and Concepts I&apos;m comfortable with.
        /// </summary>
        public static string SectionHeader1 {
            get {
                return ResourceManager.GetString("SectionHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Portfolio.
        /// </summary>
        public static string SectionHeader2 {
            get {
                return ResourceManager.GetString("SectionHeader2", resourceCulture);
            }
        }
    }
}
