//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerApp.Resources.Dog", typeof(Dog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraordinary Elsa of Flying Porkies.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best decision in my Life!.
        /// </summary>
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.working-dog.com/dogs-details/6140164/Ken-Ritakim.
        /// </summary>
        public static string KenLink {
            get {
                return ResourceManager.GetString("KenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Dad.
        /// </summary>
        public static string KenText {
            get {
                return ResourceManager.GetString("KenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.working-dog.com/dogs-details/6134677/Pokahontas-%C3%96HZBPRT-2648R-Erlacher.
        /// </summary>
        public static string PokiLink {
            get {
                return ResourceManager.GetString("PokiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Mom.
        /// </summary>
        public static string PokiText {
            get {
                return ResourceManager.GetString("PokiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.working-dog.com/dogs-details/6831554/Extraordinary-Elsa-of-Flying-Porkies.
        /// </summary>
        public static string WorkingDogLink {
            get {
                return ResourceManager.GetString("WorkingDogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See &lt;b&gt;Elsa&lt;/b&gt; on working-dog.com.
        /// </summary>
        public static string WorkingDogText {
            get {
                return ResourceManager.GetString("WorkingDogText", resourceCulture);
            }
        }
    }
}
