//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerApp.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who am i?.
        /// </summary>
        public static string HeadingAbout {
            get {
                return ResourceManager.GetString("HeadingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if(mug == empty){robin.unhappy;mug.refill();}&lt;br&gt;else{robin.happy}.
        /// </summary>
        public static string HeadingCoding {
            get {
                return ResourceManager.GetString("HeadingCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraordinary Elsa of Flying Porkies.
        /// </summary>
        public static string HeadingDog {
            get {
                return ResourceManager.GetString("HeadingDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest Teamsport on Earth.
        /// </summary>
        public static string HeadingIcehockey {
            get {
                return ResourceManager.GetString("HeadingIcehockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string HeadingIndex {
            get {
                return ResourceManager.GetString("HeadingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom on 2 wheels.
        /// </summary>
        public static string HeadingMotorcycle {
            get {
                return ResourceManager.GetString("HeadingMotorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me show you....
        /// </summary>
        public static string HeadingPhotography {
            get {
                return ResourceManager.GetString("HeadingPhotography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on my totally new Web presenece.&lt;br&gt;Please be aware, this Site is still under Maintenance.&lt;br&gt;I&apos;m working hard, to get a nice Website as soon as possible!.
        /// </summary>
        public static string IndexWelcomeText {
            get {
                return ResourceManager.GetString("IndexWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string NavAbout {
            get {
                return ResourceManager.GetString("NavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        public static string NavCoding {
            get {
                return ResourceManager.GetString("NavCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string NavDog {
            get {
                return ResourceManager.GetString("NavDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icehockey.
        /// </summary>
        public static string NavIcehockey {
            get {
                return ResourceManager.GetString("NavIcehockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string NavMotorcycle {
            get {
                return ResourceManager.GetString("NavMotorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        public static string NavPhotography {
            get {
                return ResourceManager.GetString("NavPhotography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Imprint.
        /// </summary>
        public static string NavPrivacyImprint {
            get {
                return ResourceManager.GetString("NavPrivacyImprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Photography.
        /// </summary>
        public static string PhotoProjectAnimal {
            get {
                return ResourceManager.GetString("PhotoProjectAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PhotoProjectCat {
            get {
                return ResourceManager.GetString("PhotoProjectCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape Photography.
        /// </summary>
        public static string PhotoProjectLandscape {
            get {
                return ResourceManager.GetString("PhotoProjectLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraordinary Elsa of Flying Porkies.
        /// </summary>
        public static string PhotoTitleElsa1 {
            get {
                return ResourceManager.GetString("PhotoTitleElsa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elsa is looking for something very interesting....
        /// </summary>
        public static string PhotoTitleElsa2 {
            get {
                return ResourceManager.GetString("PhotoTitleElsa2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing the Lens Ball.
        /// </summary>
        public static string PhotoTitleLandscape1 {
            get {
                return ResourceManager.GetString("PhotoTitleLandscape1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code by:.
        /// </summary>
        public static string TitleCoding {
            get {
                return ResourceManager.GetString("TitleCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Owner.
        /// </summary>
        public static string TitleDog {
            get {
                return ResourceManager.GetString("TitleDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hockey player.
        /// </summary>
        public static string TitleIcehockey {
            get {
                return ResourceManager.GetString("TitleIcehockey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Rider.
        /// </summary>
        public static string TitleMotorcycle {
            get {
                return ResourceManager.GetString("TitleMotorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography by:.
        /// </summary>
        public static string TitlePhotography {
            get {
                return ResourceManager.GetString("TitlePhotography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy &amp; Imprint of.
        /// </summary>
        public static string TitlePrivacy {
            get {
                return ResourceManager.GetString("TitlePrivacy", resourceCulture);
            }
        }
    }
}
